"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class rc_state_t(object):
    __slots__ = ["num_keys", "keys", "rocker"]

    __typenames__ = ["int8_t", "int8_t", "float"]

    __dimensions__ = [None, ["num_keys"], [4]]

    def __init__(self):
        self.num_keys = 0
        self.keys = []
        self.rocker = [ 0.0 for dim0 in range(4) ]

    def encode(self):
        buf = BytesIO()
        buf.write(rc_state_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">b", self.num_keys))
        buf.write(struct.pack('>%db' % self.num_keys, *self.keys[:self.num_keys]))
        buf.write(struct.pack('>4f', *self.rocker[:4]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != rc_state_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return rc_state_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = rc_state_t()
        self.num_keys = struct.unpack(">b", buf.read(1))[0]
        self.keys = struct.unpack('>%db' % self.num_keys, buf.read(self.num_keys))
        self.rocker = struct.unpack('>4f', buf.read(16))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if rc_state_t in parents: return 0
        tmphash = (0x46e5ec4bac613b8) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if rc_state_t._packed_fingerprint is None:
            rc_state_t._packed_fingerprint = struct.pack(">Q", rc_state_t._get_hash_recursive([]))
        return rc_state_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", rc_state_t._get_packed_fingerprint())[0]

